//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Du.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   주소가 지원 범위를 넘었어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddressOutOfRange {
            get {
                return ResourceManager.GetString("AddressOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConnectionFail {
            get {
                return ResourceManager.GetString("ConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 타임 아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개수가 지원 범위를 넘었어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CountOutOfRange {
            get {
                return ResourceManager.GetString("CountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽기에 오류가 있어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorOnRead {
            get {
                return ResourceManager.GetString("ErrorOnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인수가 잘못됐어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionArgument {
            get {
                return ResourceManager.GetString("ExceptionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽으러 들어오는데 예외가 있어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionEnterRead {
            get {
                return ResourceManager.GetString("ExceptionEnterRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽으러 들어오는데 예외가 있어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionEnterUpgradableRead {
            get {
                return ResourceManager.GetString("ExceptionEnterUpgradableRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쓰러 들어오는데 에외가 있어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionEnterWrite {
            get {
                return ResourceManager.GetString("ExceptionEnterWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지원하지 않는 기능 코드예요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FunctionCodeNotSupport {
            get {
                return ResourceManager.GetString("FunctionCodeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결부터 해야해요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GetConnectionFirst {
            get {
                return ResourceManager.GetString("GetConnectionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개수가 잘못됐어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidCount {
            get {
                return ResourceManager.GetString("InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 주소 범위가 잘못됐어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidStartAddress {
            get {
                return ResourceManager.GetString("InvalidStartAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   레지스터 배열 개수가 넷이 아니예요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegisterCountIsNotFour {
            get {
                return ResourceManager.GetString("RegisterCountIsNotFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   레지스터 배열 개수가 둘이 아니예요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegisterCountIsNotTwo {
            get {
                return ResourceManager.GetString("RegisterCountIsNotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UDP 연결이 도달할 수 없는 대상입니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UdpUnreachableDestination {
            get {
                return ResourceManager.GetString("UdpUnreachableDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DuLib.ModBusQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WhatsModBusQ {
            get {
                return ResourceManager.GetString("WhatsModBusQ", resourceCulture);
            }
        }
    }
}
